version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    # post_create_environment:
    #   # https://python-poetry.org/docs/#installing-manually
    #   - pip install poetry
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy

mkdocs:
  configuration: mkdocs.yaml
